/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan10;

import static pertemuan10.db_koneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DewaCahaya
 * TGL: 24-05-25
 */
public class frameTeman extends javax.swing.JFrame {
    
    String edtNama = "";
    DefaultTableModel TM = new DefaultTableModel();

    /**
     * Creates new form frameTeman
     */
    public frameTeman() throws SQLException {
        initComponents();
        
        TTM.setModel(TM);
        TM.addColumn("No");
        TM.addColumn("Nama Teman");
        TM.addColumn("Alamat");
        TM.addColumn("Telp");
        
        this.dtTemanList();
        
        fieldisEnabled(false);
        tombolisEnabled(false);
        cmdTambah.setEnabled(true);
        cmdTutup.setEnabled(true);
        
//        Connection cnn = koneksi();
//        PreparedStatement ps = cnn.prepareStatement("SELECT * FROM data_teman;");
//        ResultSet RS = ps.executeQuery();
//        
//        while(RS.next()){
//            txNama.setText(RS.getString("nama"));
//            txAlamat.setText(RS.getString("alamat"));
//            txTelp.setText(RS.getString("telp"));
//        }
    }

    private void fieldisEnabled(boolean opsi){
        txNama.setEditable(opsi);
        txAlamat.setEditable(opsi);
        txTelp.setEditable(opsi);
    }
    
    private void tombolisEnabled(boolean opsi){
        cmdTambah.setEnabled(opsi);
        cmdUbah.setEnabled(opsi);
        cmdHapus.setEnabled(opsi);
        cmdTutup.setEnabled(opsi);
    }
    
    private void resetForm(){
        txNama.setText("");
        txAlamat.setText("");
        txTelp.setText("");
    }
    
    private void storeData() throws SQLException{
        String nama = txNama.getText();
        String alamat = txAlamat.getText();
        String telp = txTelp.getText();
        
        Connection cnn = koneksi();
        PreparedStatement PS = cnn.prepareStatement("INSERT INTO data_teman(nama, alamat, telp) VALUES(?, ?, ?);");
        PS.setString(1, nama);
        PS.setString(2, alamat);
        PS.setString(3, telp);
        PS.executeUpdate();
        
        
    }
    
    private void updateData() throws SQLException{
        String nama = txNama.getText();
        String alamat = txAlamat.getText();
        String telp = txTelp.getText();
        
        Connection cnn = koneksi();
        PreparedStatement PS = cnn.prepareStatement("UPDATE data_teman SET nama=?, alamat=?, telp=? WHERE nama=?;");
        PS.setString(1, nama);
        PS.setString(2, alamat);
        PS.setString(3, telp);
        PS.setString(4, this.edtNama);
        PS.executeUpdate();
    }
    
    private void destroyData() throws SQLException{
        String nama = txNama.getText();
        Connection cnn = koneksi();
        PreparedStatement PS = cnn.prepareStatement("DELETE FROM data_teman WHERE nama=?;");
        PS.setString(1, nama);
        PS.executeUpdate();
    }
    
    private void dtTemanList() throws SQLException{
        Connection cnn = koneksi();
        PreparedStatement PS = cnn.prepareStatement("SELECT * FROM data_teman");
        ResultSet RS = PS.executeQuery();
        
        TM.getDataVector().removeAllElements();
        TM.fireTableDataChanged();
        
        while(RS.next()){
            Object[] dta = new Object[4];
                dta[0] = RS.getInt("id_teman");
                dta[1] = RS.getString("nama");
                dta[2] = RS.getString("alamat");
                dta[3] = RS.getString("telp");
                
                TM.addRow(dta);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txAlamat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txTelp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TTM = new javax.swing.JTable();
        cmdTambah = new javax.swing.JButton();
        cmdUbah = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();
        cmdTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Teman");

        txNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNamaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama");

        txAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txAlamatActionPerformed(evt);
            }
        });

        jLabel2.setText("Alamat");

        txTelp.setName("txTelp"); // NOI18N

        jLabel3.setText("No. Telp");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Data Teman");

        TTM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Alamat", "No Telp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TTM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TTMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TTM);

        cmdTambah.setText("Tambah");
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });

        cmdUbah.setText("Ubah");
        cmdUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUbahActionPerformed(evt);
            }
        });

        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        cmdTutup.setText("Tutup");
        cmdTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTelp)
                    .addComponent(txAlamat)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdTambah)
                        .addGap(18, 18, 18)
                        .addComponent(cmdUbah)
                        .addGap(18, 18, 18)
                        .addComponent(cmdHapus))
                    .addComponent(cmdTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txNama))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(txNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(txAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(txTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdTambah)
                            .addComponent(cmdUbah)
                            .addComponent(cmdHapus))
                        .addGap(18, 18, 18)
                        .addComponent(cmdTutup))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNamaActionPerformed

    private void txAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txAlamatActionPerformed

    private void TTMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TTMMouseClicked
//        String sql = "SELECT * FROM `data_teman` WHERE id_teman="+TTM.getValueAt( TTM.getSelectedRow(), 0)+";";
//        Connection cnn = koneksi();
//        PreparedStatement PS = null;
//        try {
//            PS = cnn.prepareStatement(sql);
//        } catch (SQLException ex) {
//            Logger.getLogger(frameTeman.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        try {
//            ResultSet rs = PS.executeQuery();
//            txNama.setText(rs.getString("nama"));
//            txAlamat.setText(rs.getString("alamat"));
//            txTelp.setText(rs.getString("telp"));
//        } catch (SQLException ex) {
//            Logger.getLogger(frameTeman.class.getName()).log(Level.SEVERE, null, ex);
//        }
        txNama.setText(TTM.getValueAt(TTM.getSelectedRow(), 1).toString());
        txAlamat.setText(TTM.getValueAt(TTM.getSelectedRow(), 2).toString());
        txTelp.setText(TTM.getValueAt(TTM.getSelectedRow(), 3).toString());
        
        cmdUbah.setEnabled(true);
        cmdHapus.setEnabled(true);
    }//GEN-LAST:event_TTMMouseClicked

    private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTambahActionPerformed
        if(cmdTambah.getText().equals("Tambah")){
            tombolisEnabled(false);
            cmdTambah.setText("Simpan");
            cmdTutup.setText("Batal");
            cmdTambah.setEnabled(true);
            cmdTutup.setEnabled(true);
            
            resetForm();
            fieldisEnabled(true);
        }else{
            cmdTambah.setText("Tambah");
            cmdTutup.setText("Tutup");
            
            try {
                storeData();
                dtTemanList();
            } catch (SQLException ex) {
                Logger.getLogger(frameTeman.class.getName()).log(Level.SEVERE, null, ex);
            }
            resetForm();
            fieldisEnabled(false);
        }
    }//GEN-LAST:event_cmdTambahActionPerformed

    private void cmdTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTutupActionPerformed
        if(cmdTutup.getText().equals("Tutup")){
                int jOpsi = JOptionPane.showOptionDialog(this, 
                   "Yakin akan menutup aplikasi?", 
                   "Konfirmasi Tutup Aplikasi", 
                   JOptionPane.YES_NO_OPTION, 
                   JOptionPane.QUESTION_MESSAGE, 
                   null, null, null);

           if(jOpsi == JOptionPane.YES_OPTION){
               System.exit(0);
           }
        }else{
            resetForm();
            fieldisEnabled(false);
            cmdTambah.setText("Tambah");
            cmdTutup.setText("Tutup");
            cmdUbah.setText("Ubah");
            cmdTambah.setEnabled(true);
            cmdUbah.setEnabled(false);
        }
       
        
    }//GEN-LAST:event_cmdTutupActionPerformed

    private void cmdUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUbahActionPerformed
        if(cmdUbah.getText().equals("Ubah")){
            cmdUbah.setText("Simpan");
            cmdTutup.setText("Batal");
            tombolisEnabled(false);
            cmdUbah.setEnabled(true);
            cmdTutup.setEnabled(true);
            fieldisEnabled(true);
            this.edtNama = txNama.getText();
        }else{
            try {
                updateData();
                dtTemanList();
            } catch (SQLException ex) {
                Logger.getLogger(frameTeman.class.getName()).log(Level.SEVERE, null, ex);
            }
            cmdUbah.setText("Ubah");
            cmdTutup.setText("Tutup");
            cmdTambah.setEnabled(true);
            cmdHapus.setEnabled(true);
        }
    }//GEN-LAST:event_cmdUbahActionPerformed

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
        String isNama = txNama.getText();
        int jOpsi = JOptionPane.showOptionDialog(this, 
                   "Yakin akan menghapus data "+isNama+"?", 
                   "Konfirmasi Hapus Data", 
                   JOptionPane.YES_NO_OPTION, 
                   JOptionPane.QUESTION_MESSAGE, 
                   null, null, null);
        
        if(jOpsi == JOptionPane.YES_OPTION){
            try {
                destroyData();
                dtTemanList();
                
                resetForm();
                cmdUbah.setEnabled(false);
                cmdHapus.setEnabled(false);
            } catch (SQLException ex) {
                Logger.getLogger(frameTeman.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmdHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frameTeman().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frameTeman.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TTM;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JButton cmdTutup;
    private javax.swing.JButton cmdUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txAlamat;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txTelp;
    // End of variables declaration//GEN-END:variables

//    private Connection koneksi() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }
}
